baseURL = 'https://hectorperalta12.github.io/mi-blog/'
languageCode = 'en-us'
defaultContentLanguage = 'en'
uglyURLs = true
title = 'My Blog'
theme = 'PaperMod'

[params]
  author = 'Your Name'
  defaultTheme = 'auto'
  showReadingTime = true
  ShowCodeCopyButtons = true
  showPostCards = true
  disableSpecial1stPost = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

